/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xenon.view.sdk;

import org.junit.Test;
import static org.junit.Assert.*;

public class ViewTest {
    @Test public void someLibraryMethodReturnsTrue() {
        View classUnderTest = new View();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
